Convert project to use Spring Boot
commit c86b61ac30c014f8bd2d3a9fa108a71da0090a51
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Fri Nov 23 11:30:50 2018 +0800

    Clean up pom.xml

    * Remove unnecessary lines
    * Add maven compiler source and target to fix error:
      Java compiler level does not match the version of the installed Java
      project facet.
      (See: https://stackoverflow.com/a/7715401)

commit 1be459a7ea39c67899a63386ddcf14dcebf8c27e
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Thu Nov 22 10:55:06 2018 +0800

    Refactor readme

    Add more detail to explanations, edit for clarity and clean up
    formatting.

commit e524d0c2cce357099507cbf2d610f556adbd41d8
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Thu Nov 22 09:55:40 2018 +0800

    Convert readme from markdown to asciidoc

    To support more features e.g. footnotes

commit 22b1334607f9ffae27f36dd8d0d5f650583c86c8
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Fri Nov 23 11:52:39 2018 +0800

    Replace JDBC with Spring Data JPA

    * Replace servlets with Spring code
      * Replace JDBC queries with Spring Repository
      * Replace HTML output with Thymeleaf + Spring
      * Restructure project
      * Remove HelloServlet
    * Annotate code with explanations
    * Add detail to readme for Spring
    * Update readme with Spring Data JPA

    commit 4b0252bab4d62d998ecc73ee22a02429eec3a814
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Wed Nov 21 16:58:24 2018 +0800

        Remove HelloServlet

    commit 52396a3727b824ce43d782a56b07920349ad68ae
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Wed Nov 21 16:45:49 2018 +0800

        Restructure project code

    commit c6a8e61627a555982d948e7049548ae90d8dbc1b
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Wed Nov 21 16:09:38 2018 +0800

        Update readme with Spring/Spring Boot

    commit 1584e7f006d9c0228ee85d2d414298b5cabc0f96
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Wed Nov 21 16:08:50 2018 +0800

        Clean up code and add explanations

    commit c5ef1e0a8ba51f2a2e7661e55c85af9f81ee6a9c
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Mon Nov 19 15:44:54 2018 +0800

        Replace QueryServlet.java with Spring+Thymeleaf code

    commit 421336d494e361332041c11bbd0d18c3e0fd162b
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Mon Nov 19 15:42:28 2018 +0800

        Add simple example of Spring + Thymeleaf

    commit 4f14f5a912679856791327d5b814913581397f90
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Mon Nov 19 15:38:48 2018 +0800

        Add Spring/Thymeleaf dependency to Maven

        For HTML templates

    commit cd72f59740097204357199e8a84717c3aced7a5f
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Mon Nov 19 14:10:44 2018 +0800

        Convert old SQL queries to use Spring

    commit effa12c242ffe9e76792d59ff5ea931c5e23e4bc
    Author: Ka Yi <chua.kayi@yahoo.com.sg>
    Date:   Fri Nov 16 16:49:06 2018 +0800

        Add Spring to MySQL

        Note that repository and other files must be in subpackage of `hello`,
        otherwise they are not included in SpringBootApplication's component
        scan. If we want to include other packages, we will need to add them
        manually to @SpringBootApplication using @ComponentScan.

        https://dzone.com/articles/spring-spring-boot-and-component-scan

commit d958d554ffc75585dbd32227bd7c504416f61ad1
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Fri Nov 16 15:18:38 2018 +0800

    Fix formatting in pom.xml

commit ecb96cb04da014c9207ca8156de75d98b19dcc5e
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Fri Nov 16 09:01:28 2018 +0800

    Add Spring-boot to project

    1. Add Spring to pom.xml, with support for .war files for Tomcat
    2. Add sample code using Spring, taken from Spring tutorial
    3. Add contextPath to application.properties so urls when app is deployed
       via mvn spring-boot:run and mvn package (war -> tomcat) are the same
    4. Update readme

commit 9b4fdfa11676df9cc6165296152f880c3de646a0
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Fri Nov 16 10:40:18 2018 +0800

    Fix blank page result for database query

    Blank page is returned for book queries. However, correct results are
    returned if myuser logs in to mysql after server starts and before query
    is submitted.

    Checking tomcat logs, we see the error message:
      java.sql.SQLNonTransientConnectionException: Public Key Retrieval is
      not allowed

    Let us add `&allowPublicKeyRetrieval=true` to the connection database
    URL[1]. This is possibly not safe for production and it is unclear why
    this works. Possibly incompatibility between JDBC driver and MySQL?
    Newer versions of MySQL use caching_sha2_password as the default
    authentication plugin for servers instead of mysql_native_password[3].
    Not sure if JDBC driver supports this.

    Other possible methods (untested):
      * Change MySQL server to use legacy method for authentication [2]
      * Change user password to use mysql_native_password [3]

    [1] https://stackoverflow.com/a/50438872
    [2] https://stackoverflow.com/a/49966020
    [3] https://stackoverflow.com/a/50433762

    To read more about Caching SHA-2 Pluggable Authentication in MySQL,
    see: https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html

commit 10df852797a02479941b18e8b1117fc355929e22
Author: Ka Yi <chua.kayi@yahoo.com.sg>
Date:   Fri Nov 16 09:19:26 2018 +0800

    Add Tomcat plugin to Maven