Fix blank page result for database query
Blank page is returned for book queries. However, correct results are
returned if myuser logs in to mysql after server starts and before query
is submitted.

Checking tomcat logs, we see the error message:
  java.sql.SQLNonTransientConnectionException: Public Key Retrieval is
  not allowed

Let us add `&allowPublicKeyRetrieval=true` to the connection database
URL[1]. This is possibly not safe for production and it is unclear why
this works. Possibly incompatibility between JDBC driver and MySQL?
Newer versions of MySQL use caching_sha2_password as the default
authentication plugin for servers instead of mysql_native_password[3].
Not sure if JDBC driver supports this.

Other possible methods (untested):
  * Change MySQL server to use legacy method for authentication [2]
  * Change user password to use mysql_native_password [3]

[1] https://stackoverflow.com/a/50438872
[2] https://stackoverflow.com/a/49966020
[3] https://stackoverflow.com/a/50433762

To read more about Caching SHA-2 Pluggable Authentication in MySQL,
see: https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html